### ISSUE TITLE
rnorsk package not available for R version 4.0.2

### ISSUE THREAD

**Issue by analaws** [ihrke/rnorsk#1]

**Comment by analaws** [comment]
Hello, just bought your book and was attempting to install the rnorsk package. Will you update it to 4.0.2 or should I revert to an earlier version of R? cheers

**Comment by analaws** [comment]
never mind, I got it to work :)

**Comment by odk022** [comment]
I bought the book now and have the same problem. I use version 4.1.2. Can you fix it?

**Comment by ihrke** [comment]
It should work with this version. I use an even newer one and it works with no trouble. Did you try this?

```r
install.packages("devtools")
devtools::install_github("ihrke/rnorsk")
```
