### ISSUE TITLE
Unable to 

### ISSUE THREAD

**Issue by BenGarb** [ihrke/rnorsk#3]
Hi

I get this errormessage when trying to download and install "rnorsk"

Downloading GitHub repo ihrke/rnorsk@HEAD
Error: Failed to install 'rnorsk' from GitHub:
  input string 89 is invalid
In addition: Warning message:
In gsub("[^/]", "", file_list) :
  unable to translate 'ihrke-rnorsk-c4c8a2c/inst/code_examples/kapittel_07-line+<aa>r_regresjon.R' to a wide string

Is there any solution?

Br

BenGarb

**Comment by ihrke** [comment]
5233682aa2c8d5d32e37eebd3798ecea1b06f52d fixes this
